### ISSUE TITLE
Async is a keyword in Python 3.7.*

### ISSUE THREAD

**Issue by kgrzadziel** [actmd/elementium#11]
Hello,

within elements.py and se.py files, there is an 'async' parameter used which is a keyword in python3.7.* version. It could be renamed to -> asynchronous.

Regards,
Kamil

**Comment by prschmid** [comment]
Hi Kamil,

That's definitely something that could be done -- likely the best way would be to make a new major version (2.0.0) with that change so that people can use the 1.x version with the old 'async' parameter. 
Thoughts?

**Comment by kgrzadziel** [comment]
Hello Patrick,

I think it would be a very good idea :)

**Comment by prschmid** [comment]
I just created a new release ([2.0.0](https://github.com/actmd/elementium/releases/tag/2.0.0)) with the `async` keyword renamed. Hope this helps!
