### ISSUE TITLE
Python 3.*

### ISSUE THREAD

**Issue by Quorce** [actmd/elementium#3]
Is there any chance for update elementium to Python 3.5?

**Comment by prschmid** [comment]
Is there something in particular that is broken or a feature that is needed
for 3.5?

**Comment by Quorce** [comment]
For now I see this:
> File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/elementium/drivers/se.py", line 96, in <lambda>
>     self.browser, context=self, fn=lambda context: [context.items[i]],
> TypeError: list indices must be integers or slices, not str

**Comment by prschmid** [comment]
Interesting, yes, that *should* be an int. I'll take a look later today and
try to put together a fix. Hopefully should be pretty straight forward.

**Comment by Quorce** [comment]
I'll fork elementium and try update it to python 3.5 in next few days... :)

**Comment by prschmid** [comment]
That works too! Looking forward to your pull request.

In the mean time I'll setup .tox file so that it's easy to test across
multiple versions locally.

http://blog.pinaxproject.com/2015/12/08/how-test-against-multiple-python-versions-parallel/

**Comment by Quorce** [comment]
PR ready.

**Comment by prschmid** [comment]
So, I just added python 3.5 testing as part of adding the tox testing support (https://github.com/actmd/elementium/tree/feature/tox-support) and it looks like it all passes (both locally and via Travis CI). Is there something you are doing differently

https://travis-ci.org/actmd/elementium/builds/153322092

**Comment by prschmid** [comment]
I'm going to close this issue as I've put in all of the relevant changes in 3d8bb8b which has been released in version 1.1.7 (8156fa4)

**Comment by Quorce** [comment]
Nice, thanks! :) Maybe in the future I will add any new feature. :)

**Comment by prschmid** [comment]
Looking forward to it!
